baseURL = "https://viangm.github.io/Biographies-of-Ura/"
languageCode = "zh-cn"
title = "有同学列传"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "有同学列传"
Content = "Biographies-of-Ura"