baseURL = "https://u.viang.qzz.io/"
languageCode = "zh-cn"
title = "有同学列传"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true

[params.label]
icon = "images/logo.png"
iconHeight = 30

[params.homeInfoParams]
Title = "有同学列传"
Content = "Biographies-of-Ura"
